import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    // Scan shared UI package for Tailwind classes
    '../../packages/ui/src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Electric Noir design system
        surface: '#0e0e0e',
        'surface-dim': '#0e0e0e',
        'surface-bright': '#2c2c2c',
        'surface-container-lowest': '#000000',
        'surface-container-low': '#131313',
        'surface-container': '#1a1919',
        'surface-container-high': '#201f1f',
        'surface-container-highest': '#262626',
        'surface-variant': '#262626',
        background: '#0e0e0e',
        'on-background': '#ffffff',
        'on-surface': '#ffffff',
        'on-surface-variant': '#adaaaa',
        primary: '#85adff',
        'primary-dim': '#0070eb',
        'primary-container': '#6c9fff',
        'primary-fixed': '#6c9fff',
        'primary-fixed-dim': '#5191ff',
        'on-primary': '#002c65',
        'on-primary-fixed': '#000000',
        'on-primary-container': '#00214f',
        'on-primary-fixed-variant': '#002a61',
        'inverse-primary': '#005bc2',
        secondary: '#7f98ff',
        'secondary-dim': '#7f98ff',
        'secondary-fixed': '#c6cfff',
        'secondary-fixed-dim': '#b4c1ff',
        'secondary-container': '#1f3da1',
        'on-secondary': '#00185e',
        'on-secondary-fixed': '#00288d',
        'on-secondary-fixed-variant': '#2c48ac',
        'on-secondary-container': '#c5ceff',
        tertiary: '#fab0ff',
        'tertiary-dim': '#e48fec',
        'tertiary-fixed': '#f39cfb',
        'tertiary-fixed-dim': '#e48fec',
        'tertiary-container': '#f39cfb',
        'on-tertiary': '#6b1f77',
        'on-tertiary-fixed': '#41004d',
        'on-tertiary-fixed-variant': '#6a1f76',
        'on-tertiary-container': '#60136d',
        outline: '#777575',
        'outline-variant': '#494847',
        error: '#ff716c',
        'error-dim': '#d7383b',
        'error-container': '#9f0519',
        'on-error': '#490006',
        'on-error-container': '#ffa8a3',
        'surface-tint': '#85adff',
        'inverse-surface': '#fcf8f8',
        'inverse-on-surface': '#565554',
      },
      fontFamily: {
        headline: ['var(--font-headline)', 'Plus Jakarta Sans', 'sans-serif'],
        body: ['var(--font-body)', 'Inter', 'sans-serif'],
        label: ['var(--font-body)', 'Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}

export default config
